# Generated by Django 5.2.4 on 2025-07-31 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Login',
                'verbose_name_plural': 'Login',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(default='Unknown', max_length=20),
            preserve_default=False,
        ),
    ]
